### ISSUE TITLE
Inconsistent deployment YAML

### ISSUE THREAD

**Issue by pa-uriza** [nigelpoulton/TheK8sBook#27]
In the section "Create a Deployment" the file showed is not the same as the one in the book 2022 version.

The book shows this yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-world
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
         image: nigelpoulton/k8sbook:1.0
         ports:
         - containerPort: 8080
```
However, the repo contains this as the `deploy.yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-test
spec:
  replicas: 10
  selector:
    matchLabels:
      chapter: services
  template:
    metadata:
      labels:
        chapter: services
    spec:
      containers:
      - name: hello-ctr
        image: nigelpoulton/k8sbook:1.0
        ports:
        - containerPort: 8080
```

**Comment by pa-uriza** [comment]
A similar thing happens with the `svc.yaml` file. This is what is in the book:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
labels:
  app: hello-world
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: hello-world
```

And the following is what is on the repo:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-test
  labels:
    chapter: services
spec:
# ipFamilyPolicy: PreferDualStack
# ipFamilies:
# - IPv4
# - IPv6
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    targetPort: 8080
    protocol: TCP
  selector:
    chapter: services
```
